### PR TITLE
Compatibility Fixes:

### PR DESCRIPTION
**Pull request by guilt**
- Add Imported Library, Def File.
- Update C Headers from Khronos.
- Add working C++ Headers from Khronos. Remove gl* to make stuff work.
- Add print_info.cpp for testing Khronos C++ Headers.
- Generate Import Library from OpenCL.dll.
- Update README.md.

### CODE REVIEW

**Comment by guilt** [comment]
Hi,

Thanks to your work I was actually able to make use of this and get a lot further.... I've also added the C++ header and updated the C one, in case you wish to look at it. Shown are the CLBlast examples running on these minimal files.

ScreenCapture-CLBlast
ScreenCapture-CLBlast2
ScreenCapture-CLBlast3
ScreenCapture-OpenCL

**Comment by arkanis** [comment]
Hi guilt,

thanks for the pull request, but I'm honestly a bit baffled by all the added stuff. The point of this repository was mostly to show that you don't need a lot of SDKs, build systems and what not to work with OpenCL.

Your file structure looks a lot more like a common MS VisualC++ project. Or maybe cmake, I'm not using either so I'm not sure. That structure might be needed for some build system or IDEs, but you don't need it for OpenCL. It's really just a DLL you have to link against and the two header files to tell the compiler what functions you expect that DLL to have. Everything else just makes it more complicated.

Additionally you don't need the Lib stuff (static import library) for MinGW. Thos libs are a MS VisualC++ thing. If you tell gcc to link against a DLL it will look at the DLL and generate the needed code to call the DLL functions automatically (using `gendef` if I recall correctly). It's interesting to know but there's no point in doing that manually as far as I know. You can look at [comment #10 and #11](http://arkanis.de/weblog/2014-11-25-minimal-opencl-development-on-windows#comment-2018-12-08-08-42-18-stephan) of the blog post for details and further links.

Also you don't need the C++ bindings to work with OpenCL. I guess a lot of C++ developers like them, but you really don't need them to work with OpenCL. The C headers should work just fine. And bindings have the annoying tendency to break and make life more complicated.

Since you mentioned CLBlast: Note that CLBlast is a C++ project and it uses CMake. And this means all the fun of telling your build system where to find stuff. In case of that project it seems you have to tell it where the OpenCL header files are. At least according to the documentation in https://github.com/CNugteren/CLBlast/blob/master/cmake/Modules/FindOpenCL.cmake.

> In case OpenCL is not installed in the default directory, set the OPENCL_ROOT variable to point to
the root of OpenCL, such that 'OpenCL/cl.h' or 'CL/cl.h' can be found in $OPENCL_ROOT/include.
This can either be done using an environmental variable (e.g. export OPENCL_ROOT=/path/to/opencl)
or using a CMake variable (e.g. cmake -DOPENCL_ROOT=/path/to/opencl ..).

All in all I don't see why that pull request is necessary. I'll close it for now. Please let me know if I missed anything.

**Comment by guilt** [comment]
Hi @arkanis,

Thank you for taking a look. I did not expect a reply, given this stuff was updated years ago.

This PR is documentation. Just adding a few points:

- Linking against the DLL does work. On a build system with cross compilation, one does not need to have access to the actual DLL. It helps to keep the .a file in such a case. I do not wish to ship any particular vendor's OpenCL DLL in any such case to such CI/CD setups, so this works exactly like how `-lopengl32` would. 
- In my case though, I am working with an archived driver in circumstances not normally supported by the vendor (see: https://blog.karthikkumar.org/usability-of-old-computers-f06a7f00f72e) and I'm not sure distributing that DLL may be of value to build users.
- With CLBlast, the file you linked to, they expect to `find_library` in a SDK directory. The current approach helped me get the build  working correctly without too many issues, even if this stuff is like the outdated way of building things.
- The C++ version of the header I'm using it to build a lot of different projects to test their compatibility with them. Apparently many people's OpenCL projects seem to use those and Khronos seems to be distributing those too.
- I tried generating an import library with dlltool / gendef. I found that a lot of symbols were missing partly due to the `@4` business needed to link corectly. So this explicit def file works reasonably well for now and added to the PR.

In case anyone finds the same issues I did, they can definitely look at this and know what happened. Or if they have better workarounds, they could post them here.

Thank you though, didn't expect it to rise back from the dead. 😊

**Comment by arkanis** [comment]
Interesting, thanks for the clarification. :)

The CI/CD usercase for .def files / libs makes sense. Same for the archived driver. Seems like a good way to target a specific OpenCL version without keeping a DLL around. But that's hardly something for a minimal OpenCL example where every user already has a local OpenCL DLL installed anyway.

Pretty interesting blog post and a quite interesting project (that also explains the UIs in the screenshots). That brought back memories (especially foobar2000). Unfortunately you stumbled right into the great joy Windows calling conventions on 32 bit x86 (or rather the whole bloody mess of it). If I remember correctly there was a special case where you can't differentiate between the C and stdcall calling convention by just inspecting the functions machine code. Unfortunately the WinAPI contained functions using both cases and thanks to lawyers and licensing issues you were not allowed to just pull the information from the Windows SDK. Hence the GCC tools had to assume something and users then had to patch it if something exploded. But that was a long time ago and I'm not sure I remember all that correctly. I'm really glad we left all that behind with 64 bit x86. Doesn't help in your case, unfortunately. But I really hope it's save to assume that every OpenCL DLL is using stdcall. If not... dang, OpenCL isn't _that_ old...

Hm, maybe you should write a blog post about getting CLBlast to work on a retro PC with an old OS and archived graphics driver. Its more a thing of providing GCC with all linking information (the .def file) and packaging that with the OpenCL headers matching the driver version (1.0?) in a way that CLBlast works. Actually a pretty interesting thing and the push request here doesn't do it justice. It just doesn't match the purpose of this repository.

**Pull request closed without merging**
